// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0C-ek4Tm4s0_TbhNUhk1y-vFG9HLDb2Q',
    appId: '1:958002438784:web:2d882d3680707fabcf7c65',
    messagingSenderId: '958002438784',
    projectId: 'cmsc23-todo-app-abramillano',
    authDomain: 'cmsc23-todo-app-abramillano.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-abramillano.appspot.com',
    measurementId: 'G-J13ML8QC93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7PcgxeXoboCG86HSntuqjAm3Wa_l_q1E',
    appId: '1:958002438784:android:12ced58e2fbf8ed4cf7c65',
    messagingSenderId: '958002438784',
    projectId: 'cmsc23-todo-app-abramillano',
    storageBucket: 'cmsc23-todo-app-abramillano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1zZMGnwvB9UKYgz7dBHigpVBeZPhwOso',
    appId: '1:958002438784:ios:b73c905ac5973836cf7c65',
    messagingSenderId: '958002438784',
    projectId: 'cmsc23-todo-app-abramillano',
    storageBucket: 'cmsc23-todo-app-abramillano.appspot.com',
    iosClientId: '958002438784-sk85657o3op5e1ag77r5q3em36lu4vjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1zZMGnwvB9UKYgz7dBHigpVBeZPhwOso',
    appId: '1:958002438784:ios:b73c905ac5973836cf7c65',
    messagingSenderId: '958002438784',
    projectId: 'cmsc23-todo-app-abramillano',
    storageBucket: 'cmsc23-todo-app-abramillano.appspot.com',
    iosClientId: '958002438784-sk85657o3op5e1ag77r5q3em36lu4vjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
